[variables]
NIXPACKS_PATH = "apps/web"

[phases.setup]
nixPkgs = ["nodejs_20"]
nixLibs = ["glibc"]

[phases.install]
dependsOn = ["setup"]
cmds = ["cd apps/web && npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["cd apps/web && npm run build"]

[start]
cmd = "cd apps/web && npm start"
